import type { ServerSpec } from '../types';

/** Deterministic FNV-1a hash so generated UUIDs are stable across restarts. */
function hash(str: string): number {
  let h = 2166136261;
  for (let i = 0; i < str.length; i++) {
    h ^= str.charCodeAt(i);
    h = Math.imul(h, 16777619);
  }
  return h | 0;
}

/** Deterministic UUID from a seed — the fleet identity persists across restarts. */
export function uuid(seed: string): string {
  const x = (n: number) => (n >>> 0).toString(16).padStart(8, '0');
  const a = hash(`${seed}::1`);
  const b = hash(`${seed}::2`);
  const c = hash(`${seed}::3`);
  const d = hash(`${seed}::4`);
  return `${x(a).slice(0, 8)}-${x(b).slice(0, 4)}-4${x(b).slice(4, 7)}-${x(c).slice(0, 4)}-${x(c).slice(4, 8)}${x(d).slice(0, 8)}`;
}

/** Display names for the demo clusters referenced by `clusterId`. */
export const CLUSTER_NAMES: Record<string, string> = {
  'lab-proxmox': 'HomeLab Proxmox Cluster',
};

export interface MockContainerDef {
  id: string;
  name: string;
  running: boolean;
  image: string;
  ports: string[];
}

export const DOCKER01_CONTAINERS: MockContainerDef[] = [
  { id: 'c01a1b2c3d01', name: 'homelab-frontend', running: true, image: 'homelab/frontend:v1.0.17', ports: ['3000:3000/tcp'] },
  { id: 'c01a1b2c3d02', name: 'homelab-backend', running: true, image: 'homelab/backend:v1.0.17', ports: ['4000:4000/tcp'] },
  { id: 'c01a1b2c3d03', name: 'uptime-kuma', running: true, image: 'louislam/uptime-kuma:latest', ports: ['3001:3001/tcp'] },
  { id: 'c01a1b2c3d04', name: 'grafana', running: true, image: 'grafana/grafana-oss:latest', ports: ['3002:3000/tcp'] },
  { id: 'c01a1b2c3d05', name: 'prometheus', running: true, image: 'prom/prometheus:latest', ports: ['9090:9090/tcp'] },
];

export const DOCKER02_CONTAINERS: MockContainerDef[] = [
  { id: 'c02a1b2c3d11', name: 'plex', running: true, image: 'plexinc/pms-docker:latest', ports: ['32400:32400/tcp'] },
  { id: 'c02a1b2c3d12', name: 'jellyfin', running: true, image: 'jellyfin/jellyfin:latest', ports: ['8096:8096/tcp'] },
  { id: 'c02a1b2c3d13', name: 'sonarr', running: true, image: 'linuxserver/sonarr:latest', ports: ['8989:8989/tcp'] },
  { id: 'c02a1b2c3d14', name: 'radarr', running: true, image: 'linuxserver/radarr:latest', ports: ['7878:7878/tcp'] },
  { id: 'c02a1b2c3d15', name: 'transmission', running: true, image: 'linuxserver/transmission:latest', ports: ['9091:9091/tcp', '51413:51413/tcp'] },
];

export const DOCKER03_CONTAINERS: MockContainerDef[] = [
  { id: 'c03a1b2c3d21', name: 'vaultwarden', running: true, image: 'vaultwarden/server:latest', ports: ['8080:80/tcp'] },
  { id: 'c03a1b2c3d22', name: 'nextcloud', running: true, image: 'nextcloud:apache', ports: ['8081:80/tcp'] },
  { id: 'c03a1b2c3d23', name: 'postgres', running: true, image: 'postgres:16-alpine', ports: ['5432:5432/tcp'] },
  { id: 'c03a1b2c3d24', name: 'redis', running: true, image: 'redis:7-alpine', ports: ['6379:6379/tcp'] },
  { id: 'c03a1b2c3d25', name: 'nginx-proxy-manager', running: true, image: 'jc21/nginx-proxy-manager:latest', ports: ['80:80/tcp', '443:443/tcp', '81:81/tcp'] },
];

/** Map of serverId -> container list for Docker hosts */
export const MOCK_SERVER_CONTAINERS: Record<string, MockContainerDef[]> = {
  docker01: DOCKER01_CONTAINERS,
  docker02: DOCKER02_CONTAINERS,
  docker03: DOCKER03_CONTAINERS,
};

/**
 * Authoritative Master Catalog of the Simulated Fleet:
 * - 3 Proxmox Cluster Nodes (pve0, pve1, pve2)
 * - 9 Diverse Virtual Machines (Debian, Ubuntu, Fedora, Windows Server, TrueNAS, OPNsense)
 * - 2 Physical Infrastructure Spine Nodes (Gateway, Switch01)
 */
export const SERVER_SPECS: ServerSpec[] = [
  // ══════════════════════════════════════════════════════════════════════
  // PROXMOX CLUSTER NODE 1 (pve0: Primary Hypervisor)
  // ══════════════════════════════════════════════════════════════════════
  {
    id: 'pve0',
    serverId: uuid('pve0'),
    hostname: 'pve0.lab',
    name: 'PVE0 (Primary Compute)',
    logo: '🟩',
    capabilities: ['virtualization', 'containerization'],
    clusterId: 'lab-proxmox',
    os: 'Proxmox VE 8.2',
    description: 'Primary virtualization cluster node — AMD Ryzen 9 5950X',
    role: 'hypervisor',
    ip: '192.168.1.10',
    location: 'Rack R1 / U32',
    cpuModel: 'AMD Ryzen 9 5950X (16C/32T)',
    cpuCores: 32,
    ramTotalGb: 128,
    diskTotalGb: 8192,
    sensors: [
      { kind: 'cpu_temp', label: 'CPU Temperature', unit: '°C', base: 48, variance: 4, correlatesWith: 'temp', correlation: 0.9, warningThreshold: 78, criticalThreshold: 88 },
      { kind: 'gpu_temp', label: 'GPU Temperature', unit: '°C', base: 44, variance: 5, correlatesWith: 'cpu', correlation: 0.45, warningThreshold: 82, criticalThreshold: 92 },
      { kind: 'gpu_usage', label: 'GPU Utilization', unit: '%', base: 14, variance: 10, correlatesWith: 'cpu', correlation: 0.5, warningThreshold: 90, criticalThreshold: 98 },
      { kind: 'fan_rpm', label: 'Chassis Fan RPM', unit: 'rpm', base: 850, variance: 60, correlatesWith: 'temp', correlation: 0.7, warningThreshold: 2400, criticalThreshold: 2600 },
      { kind: 'power_consumption', label: 'Power Draw', unit: 'W', base: 95, variance: 18, correlatesWith: 'cpu', correlation: 0.6, warningThreshold: 320, criticalThreshold: 360 },
      { kind: 'nvme_temp', label: 'NVMe Temp', unit: '°C', base: 42, variance: 3, correlatesWith: 'cpu', correlation: 0.35, warningThreshold: 68, criticalThreshold: 74 },
    ],
    profile: {
      baseCpu: 35,
      cpuAmplitude: 14,
      cpuNoise: 5,
      baseRamGb: 68,
      ramDriftGb: 4,
      baseTemp: 48,
      tempVariance: 4,
      baseNetUpMbps: 140,
      baseNetDownMbps: 450,
      netBurstRate: 0.2,
      processes: 224,
      containers: 10,
      vms: 3,
      reliability: 0.999,
    },
  },

  // ─── pve0 > VM 1: docker01 (Debian 12 Docker Host) ──────────────────
  {
    id: 'docker01',
    serverId: uuid('docker01'),
    hostname: 'docker01.lab',
    name: 'docker01',
    logo: '🐳',
    capabilities: ['containerization'],
    clusterId: 'lab-proxmox',
    parentId: 'pve0',
    os: 'Debian 12 (Bookworm)',
    description: 'Core application host — HomeLab-OS + Prometheus stack',
    role: 'docker',
    ip: '192.168.1.30',
    location: 'pve0 / VMID 100',
    cpuModel: 'KVM Virtual CPU (8 vCPU)',
    cpuCores: 8,
    ramTotalGb: 32,
    diskTotalGb: 1024,
    sensors: [],
    profile: {
      baseCpu: 36,
      cpuAmplitude: 16,
      cpuNoise: 6,
      baseRamGb: 18.5,
      ramDriftGb: 1.5,
      baseTemp: 48,
      tempVariance: 4,
      baseNetUpMbps: 65,
      baseNetDownMbps: 210,
      netBurstRate: 0.22,
      processes: 148,
      containers: 5,
      vms: 0,
      reliability: 0.995,
    },
  },

  // ─── pve0 > VM 2: docker02 (Ubuntu 24.04 Media Host) ────────────────
  {
    id: 'docker02',
    serverId: uuid('docker02'),
    hostname: 'docker02.lab',
    name: 'docker02',
    logo: '🐳',
    capabilities: ['containerization'],
    clusterId: 'lab-proxmox',
    parentId: 'pve0',
    os: 'Ubuntu 24.04 LTS',
    description: 'Media & automation host — Plex, Jellyfin, Sonarr',
    role: 'docker',
    ip: '192.168.1.31',
    location: 'pve0 / VMID 101',
    cpuModel: 'KVM Virtual CPU (8 vCPU)',
    cpuCores: 8,
    ramTotalGb: 32,
    diskTotalGb: 2048,
    sensors: [],
    profile: {
      baseCpu: 28,
      cpuAmplitude: 18,
      cpuNoise: 7,
      baseRamGb: 21.2,
      ramDriftGb: 2.0,
      baseTemp: 48,
      tempVariance: 4,
      baseNetUpMbps: 55,
      baseNetDownMbps: 175,
      netBurstRate: 0.25,
      processes: 136,
      containers: 5,
      vms: 0,
      reliability: 0.994,
    },
  },

  // ─── pve0 > VM 3: dev-fedora01 (Fedora 40 Dev Runner) ───────────────
  {
    id: 'dev-fedora01',
    serverId: uuid('dev-fedora01'),
    hostname: 'fedora-dev.lab',
    name: 'dev-fedora01',
    logo: '🎩',
    capabilities: ['virtualization'],
    clusterId: 'lab-proxmox',
    parentId: 'pve0',
    os: 'Fedora Server 40',
    description: 'Fedora Linux build environment & CI execution runner',
    role: 'server',
    ip: '192.168.1.32',
    location: 'pve0 / VMID 102',
    cpuModel: 'KVM Virtual CPU (8 vCPU)',
    cpuCores: 8,
    ramTotalGb: 16,
    diskTotalGb: 256,
    sensors: [],
    profile: {
      baseCpu: 18,
      cpuAmplitude: 14,
      cpuNoise: 5,
      baseRamGb: 8.4,
      ramDriftGb: 1.0,
      baseTemp: 48,
      tempVariance: 4,
      baseNetUpMbps: 35,
      baseNetDownMbps: 95,
      netBurstRate: 0.18,
      processes: 94,
      containers: 0,
      vms: 0,
      reliability: 0.998,
    },
  },

  // ══════════════════════════════════════════════════════════════════════
  // PROXMOX CLUSTER NODE 2 (pve1: Infrastructure & Network)
  // ══════════════════════════════════════════════════════════════════════
  {
    id: 'pve1',
    serverId: uuid('pve1'),
    hostname: 'pve1.lab',
    name: 'PVE1 (App & Security)',
    logo: '🟩',
    capabilities: ['virtualization', 'containerization'],
    clusterId: 'lab-proxmox',
    os: 'Proxmox VE 8.2',
    description: 'Secondary virtualization cluster node — Intel i7-13700K',
    role: 'hypervisor',
    ip: '192.168.1.11',
    location: 'Rack R1 / U30',
    cpuModel: 'Intel Core i7-13700K (16C/24T)',
    cpuCores: 24,
    ramTotalGb: 64,
    diskTotalGb: 4096,
    sensors: [
      { kind: 'cpu_temp', label: 'CPU Temperature', unit: '°C', base: 43, variance: 3, correlatesWith: 'temp', correlation: 0.85, warningThreshold: 78, criticalThreshold: 88 },
      { kind: 'fan_rpm', label: 'CPU Cooler RPM', unit: 'rpm', base: 920, variance: 80, correlatesWith: 'temp', correlation: 0.7, warningThreshold: 2400, criticalThreshold: 2600 },
      { kind: 'power_consumption', label: 'Power Draw', unit: 'W', base: 68, variance: 14, correlatesWith: 'cpu', correlation: 0.6, warningThreshold: 250, criticalThreshold: 290 },
      { kind: 'nvme_temp', label: 'NVMe Temp', unit: '°C', base: 40, variance: 3, correlatesWith: 'cpu', correlation: 0.35, warningThreshold: 68, criticalThreshold: 74 },
    ],
    profile: {
      baseCpu: 22,
      cpuAmplitude: 10,
      cpuNoise: 4,
      baseRamGb: 34,
      ramDriftGb: 2,
      baseTemp: 43,
      tempVariance: 3,
      baseNetUpMbps: 85,
      baseNetDownMbps: 280,
      netBurstRate: 0.15,
      processes: 164,
      containers: 5,
      vms: 3,
      reliability: 0.999,
    },
  },

  // ─── pve1 > VM 1: docker03 (Debian 12 Database Host) ────────────────
  {
    id: 'docker03',
    serverId: uuid('docker03'),
    hostname: 'docker03.lab',
    name: 'docker03',
    logo: '🐳',
    capabilities: ['containerization'],
    clusterId: 'lab-proxmox',
    parentId: 'pve1',
    os: 'Debian 12 (Bookworm)',
    description: 'Productivity & database host — Nextcloud, Vaultwarden, Postgres',
    role: 'docker',
    ip: '192.168.1.40',
    location: 'pve1 / VMID 200',
    cpuModel: 'KVM Virtual CPU (8 vCPU)',
    cpuCores: 8,
    ramTotalGb: 24,
    diskTotalGb: 1024,
    sensors: [],
    profile: {
      baseCpu: 24,
      cpuAmplitude: 12,
      cpuNoise: 5,
      baseRamGb: 14.8,
      ramDriftGb: 1.2,
      baseTemp: 43,
      tempVariance: 3,
      baseNetUpMbps: 45,
      baseNetDownMbps: 140,
      netBurstRate: 0.18,
      processes: 122,
      containers: 5,
      vms: 0,
      reliability: 0.996,
    },
  },

  // ─── pve1 > VM 2: firewall01 (OPNsense Virtual Appliance) ───────────
  {
    id: 'firewall01',
    serverId: uuid('firewall01'),
    hostname: 'firewall01.lab',
    name: 'firewall01',
    logo: '🛡️',
    capabilities: ['gateway'],
    clusterId: 'lab-proxmox',
    parentId: 'pve1',
    os: 'OPNsense 24.7',
    description: 'Dedicated virtual network firewall & DNS filtering appliance',
    role: 'network',
    ip: '192.168.1.41',
    location: 'pve1 / VMID 201',
    cpuModel: 'KVM Virtual CPU (4 vCPU)',
    cpuCores: 4,
    ramTotalGb: 8,
    diskTotalGb: 64,
    sensors: [],
    profile: {
      baseCpu: 11,
      cpuAmplitude: 8,
      cpuNoise: 3,
      baseRamGb: 3.4,
      ramDriftGb: 0.4,
      baseTemp: 43,
      tempVariance: 3,
      baseNetUpMbps: 120,
      baseNetDownMbps: 310,
      netBurstRate: 0.28,
      processes: 46,
      containers: 0,
      vms: 0,
      reliability: 0.999,
    },
  },

  // ─── pve1 > VM 3: win-server01 (Windows Server 2022) ────────────────
  {
    id: 'win-server01',
    serverId: uuid('win-server01'),
    hostname: 'win-srv01.lab',
    name: 'win-server01',
    logo: '🪟',
    capabilities: ['server'],
    clusterId: 'lab-proxmox',
    parentId: 'pve1',
    os: 'Windows Server 2022 Datacenter',
    description: 'Windows Active Directory domain controller & RDP management host',
    role: 'server',
    ip: '192.168.1.42',
    location: 'pve1 / VMID 202',
    cpuModel: 'KVM Virtual CPU (8 vCPU)',
    cpuCores: 8,
    ramTotalGb: 32,
    diskTotalGb: 512,
    sensors: [],
    profile: {
      baseCpu: 15,
      cpuAmplitude: 9,
      cpuNoise: 4,
      baseRamGb: 16.4,
      ramDriftGb: 1.8,
      baseTemp: 43,
      tempVariance: 3,
      baseNetUpMbps: 30,
      baseNetDownMbps: 85,
      netBurstRate: 0.12,
      processes: 118,
      containers: 0,
      vms: 0,
      reliability: 0.997,
    },
  },

  // ══════════════════════════════════════════════════════════════════════
  // PROXMOX CLUSTER NODE 3 (pve2: Storage & Backup)
  // ══════════════════════════════════════════════════════════════════════
  {
    id: 'pve2',
    serverId: uuid('pve2'),
    hostname: 'pve2.lab',
    name: 'PVE2 (Storage & Backup)',
    logo: '🟩',
    capabilities: ['virtualization', 'storage'],
    clusterId: 'lab-proxmox',
    os: 'Proxmox VE 8.2',
    description: 'Storage hypervisor cluster node — Intel Xeon E-2388G',
    role: 'hypervisor',
    ip: '192.168.1.12',
    location: 'Rack R1 / U28',
    cpuModel: 'Intel Xeon E-2388G (8C/16T)',
    cpuCores: 16,
    ramTotalGb: 64,
    diskTotalGb: 32768,
    sensors: [
      { kind: 'cpu_temp', label: 'CPU Temperature', unit: '°C', base: 39, variance: 3, correlatesWith: 'temp', correlation: 0.85, warningThreshold: 75, criticalThreshold: 85 },
      { kind: 'disk_temp', label: 'SAS Array Temp (avg)', unit: '°C', base: 34, variance: 2, correlatesWith: 'net', correlation: 0.2, warningThreshold: 50, criticalThreshold: 56 },
      { kind: 'fan_rpm', label: 'Chassis Fan RPM', unit: 'rpm', base: 750, variance: 50, correlatesWith: 'temp', correlation: 0.6, warningThreshold: 2200, criticalThreshold: 2500 },
      { kind: 'power_consumption', label: 'Power Draw', unit: 'W', base: 72, variance: 12, correlatesWith: 'cpu', correlation: 0.55, warningThreshold: 280, criticalThreshold: 320 },
    ],
    profile: {
      baseCpu: 16,
      cpuAmplitude: 8,
      cpuNoise: 3,
      baseRamGb: 48,
      ramDriftGb: 2,
      baseTemp: 39,
      tempVariance: 3,
      baseNetUpMbps: 180,
      baseNetDownMbps: 420,
      netBurstRate: 0.18,
      processes: 112,
      containers: 0,
      vms: 3,
      reliability: 0.999,
    },
  },

  // ─── pve2 > VM 1: nas01 (TrueNAS SCALE Enterprise ZFS) ──────────────
  {
    id: 'nas01',
    serverId: uuid('nas01'),
    hostname: 'nas01.lab',
    name: 'nas01',
    logo: '🗄️',
    capabilities: ['storage'],
    clusterId: 'lab-proxmox',
    parentId: 'pve2',
    os: 'TrueNAS SCALE 24.04',
    description: 'Dedicated enterprise ZFS storage appliance — NFS / SMB pools',
    role: 'storage',
    ip: '192.168.1.50',
    location: 'pve2 / VMID 300',
    cpuModel: 'KVM Virtual CPU (8 vCPU)',
    cpuCores: 8,
    ramTotalGb: 32,
    diskTotalGb: 24576,
    sensors: [],
    profile: {
      baseCpu: 14,
      cpuAmplitude: 9,
      cpuNoise: 4,
      baseRamGb: 26.5,
      ramDriftGb: 1.5,
      baseTemp: 39,
      tempVariance: 3,
      baseNetUpMbps: 190,
      baseNetDownMbps: 480,
      netBurstRate: 0.25,
      processes: 88,
      containers: 0,
      vms: 0,
      reliability: 0.998,
    },
  },

  // ─── pve2 > VM 2: backup01 (Proxmox Backup Server) ──────────────────
  {
    id: 'backup01',
    serverId: uuid('backup01'),
    hostname: 'backup01.lab',
    name: 'backup01',
    logo: '💾',
    capabilities: ['storage'],
    clusterId: 'lab-proxmox',
    parentId: 'pve2',
    os: 'Debian 12 (Proxmox Backup Server)',
    description: 'Enterprise deduplicated backup server — cluster snapshots',
    role: 'server',
    ip: '192.168.1.51',
    location: 'pve2 / VMID 301',
    cpuModel: 'KVM Virtual CPU (4 vCPU)',
    cpuCores: 4,
    ramTotalGb: 16,
    diskTotalGb: 8192,
    sensors: [],
    profile: {
      baseCpu: 9,
      cpuAmplitude: 7,
      cpuNoise: 3,
      baseRamGb: 7.2,
      ramDriftGb: 0.8,
      baseTemp: 39,
      tempVariance: 3,
      baseNetUpMbps: 80,
      baseNetDownMbps: 160,
      netBurstRate: 0.15,
      processes: 52,
      containers: 0,
      vms: 0,
      reliability: 0.999,
    },
  },

  // ─── pve2 > VM 3: util-debian01 (Debian 12 Utility Host) ────────────
  {
    id: 'util-debian01',
    serverId: uuid('util-debian01'),
    hostname: 'util-debian01.lab',
    name: 'util-debian01',
    logo: '🐧',
    capabilities: ['server'],
    clusterId: 'lab-proxmox',
    parentId: 'pve2',
    os: 'Debian 12 (Bookworm)',
    description: 'Lightweight utility & automation runner — Ansible & Cron worker',
    role: 'server',
    ip: '192.168.1.52',
    location: 'pve2 / VMID 302',
    cpuModel: 'KVM Virtual CPU (2 vCPU)',
    cpuCores: 2,
    ramTotalGb: 4,
    diskTotalGb: 128,
    sensors: [],
    profile: {
      baseCpu: 6,
      cpuAmplitude: 5,
      cpuNoise: 2,
      baseRamGb: 1.8,
      ramDriftGb: 0.3,
      baseTemp: 39,
      tempVariance: 3,
      baseNetUpMbps: 20,
      baseNetDownMbps: 45,
      netBurstRate: 0.1,
      processes: 38,
      containers: 0,
      vms: 0,
      reliability: 0.999,
    },
  },

  // ══════════════════════════════════════════════════════════════════════
  // PHYSICAL INFRASTRUCTURE SPINE (Gateway & Managed Core Switch)
  // ══════════════════════════════════════════════════════════════════════
  {
    id: 'gateway',
    serverId: uuid('gateway'),
    hostname: 'gateway.lab',
    name: 'Gateway (Edge Router)',
    logo: '🛡️',
    capabilities: ['gateway'],
    clusterId: null,
    os: 'OPNsense 24.7',
    description: 'Physical core edge router / firewall appliance',
    role: 'gateway',
    ip: '192.168.1.1',
    location: 'Rack R1 / U1',
    cpuModel: 'Intel N5105 Quad-Core',
    cpuCores: 4,
    ramTotalGb: 16,
    diskTotalGb: 128,
    sensors: [
      { kind: 'cpu_temp', label: 'CPU Temperature', unit: '°C', base: 45, variance: 4, correlatesWith: 'temp', correlation: 0.9, warningThreshold: 78, criticalThreshold: 88 },
      { kind: 'power_consumption', label: 'Power Draw', unit: 'W', base: 12, variance: 3, correlatesWith: 'cpu', correlation: 0.5, warningThreshold: 25, criticalThreshold: 30 },
    ],
    profile: {
      baseCpu: 12,
      cpuAmplitude: 8,
      cpuNoise: 3,
      baseRamGb: 6.2,
      ramDriftGb: 0.5,
      baseTemp: 45,
      tempVariance: 4,
      baseNetUpMbps: 380,
      baseNetDownMbps: 950,
      netBurstRate: 0.3,
      processes: 62,
      containers: 0,
      vms: 0,
      reliability: 0.999,
    },
  },

  {
    id: 'switch01',
    serverId: uuid('switch01'),
    hostname: 'switch01.lab',
    name: 'Switch01 (UniFi Core)',
    logo: '🔀',
    capabilities: ['switching'],
    clusterId: null,
    os: 'Ubiquiti UniFi USW-Pro-24',
    description: '24-port PoE+ Layer-3 managed distribution switch',
    role: 'switch',
    ip: '192.168.1.2',
    location: 'Rack R1 / U4',
    cpuModel: 'MIPS SoC Core Processor',
    cpuCores: 2,
    ramTotalGb: 2,
    diskTotalGb: 16,
    sensors: [
      { kind: 'power_consumption', label: 'PoE Total Budget', unit: 'W', base: 92, variance: 18, correlatesWith: 'net', correlation: 0.3, warningThreshold: 380, criticalThreshold: 400 },
      { kind: 'fan_rpm', label: 'Cooling Fan RPM', unit: 'rpm', base: 1100, variance: 70, correlatesWith: 'temp', correlation: 0.5, warningThreshold: 2400, criticalThreshold: 2700 },
    ],
    profile: {
      baseCpu: 6,
      cpuAmplitude: 5,
      cpuNoise: 2,
      baseRamGb: 0.85,
      ramDriftGb: 0.1,
      baseTemp: 37,
      tempVariance: 2,
      baseNetUpMbps: 550,
      baseNetDownMbps: 920,
      netBurstRate: 0.35,
      processes: 14,
      containers: 0,
      vms: 0,
      reliability: 0.999,
    },
  },
];

export const DEFAULT_SERVER = 'pve0';

/** Boot-time uptimes (seconds) so the numbers look like a real running lab. */
export const INITIAL_UPTIME_SECONDS: Record<string, number> = {
  pve0: 124 * 24 * 3600 + 3600 * 4,
  pve1: 89 * 24 * 3600 + 3600 * 12,
  pve2: 156 * 24 * 3600 + 3600 * 8,
  docker01: 42 * 24 * 3600 + 3600 * 9,
  docker02: 30 * 24 * 3600 + 3600 * 5,
  'dev-fedora01': 19 * 24 * 3600 + 3600 * 3,
  docker03: 28 * 24 * 3600 + 3600 * 18,
  firewall01: 89 * 24 * 3600 + 3600 * 11,
  'win-server01': 45 * 24 * 3600 + 3600 * 14,
  nas01: 156 * 24 * 3600 + 3600 * 6,
  backup01: 110 * 24 * 3600 + 3600 * 2,
  'util-debian01': 64 * 24 * 3600 + 3600 * 7,
  gateway: 89 * 24 * 3600 + 3600 * 22,
  switch01: 365 * 24 * 3600,
};
